version: '3.7'

services:
  maze.consul:
    image: consul
    ports:
      - 48500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - app-network
  maze.db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network
  maze.curl.consul:
    image: byrnedo/alpine-curl
    command: -X PUT --data
      '{
      "db_name":"mazedb",
      "db_URI":"mongodb://maze.db:27017"
      }'
      http://maze.consul:8500/v1/kv/maze_config
    depends_on:
      - maze.consul
    networks:
      - app-network
  maze.app:
    build: .
    ports:
      - 48080:8080
    command: [
        "-consul.addr", "maze.consul:8500"
    ]
    depends_on:
      - maze.db
      - maze.curl.consul
      - maze.consul
    networks:
      - app-network

networks:
  app-network:
    external:
      name: local-docker-dev-network


volumes:
  mongodb_data_container: