version: '3.7'

services:
  maze.db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network
  maze.app:
    build: .
    ports:
      - 48080:8080
    depends_on:
      - maze.db
    networks:
      - app-network

networks:
  app-network:
    external:
      name: local-docker-dev-network


volumes:
  mongodb_data_container: